import type { Metadata } from "next";
import { Merriweather, Playfair_Display } from "next/font/google";

import "./globals.css";

import Container from "@/components/Container";
import NavBar from "@/components/NavBar";
import NavBarItem from "@/components/NavBarItem";

const merriweatherFont = Merriweather({
  variable: '--font-title',
  subsets: ['latin'],
  weight: ['300','400', '700'],
});

const playfairDisplayFont = Playfair_Display({
  variable: '--font-subtitle',
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${merriweatherFont.variable} ${playfairDisplayFont.variable}`}>
        <Container>
          <NavBar>
            <NavBarItem href="/">Inicio</NavBarItem>
              <NavBarItem href="/poemas">Poemas</NavBarItem>
              <NavBarItem href="/pinturas">Pinturas</NavBarItem>
              <NavBarItem href="/programacion">Tips de programación</NavBarItem>
            </NavBar>
          {children}
        </Container>
      </body>
    </html>
  );
}
